name: Premarket Microcap Companies (Intrinio)

on:
  schedule:
    - cron: '0 7 * * 1' # 3 AM EST is 7 AM UTC

jobs:
  fetch_premarket_microcaps:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas

    - name: Fetch premarket microcaps
      run: python fetch_premarket_microcaps_intrinio.py

    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add premarket_microcaps.md
        git add $(date +'%Y/%m/%d')/*.md
        git commit -m "Update premarket microcap companies list"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
