name: POLYGON Premarket Small Cap Companies

on:
  schedule:
    - cron: '0 6 * * 1' # 2 AM EST is 6 AM UTC
  workflow_dispatch:

jobs:
  fetch_premarket_smallcaps:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas

    - name: Fetch premarket small caps
      run: python APIs/POLYGON/fetch_premarket_smallcaps.py
      env:
        POLYGON_TOKEN: ${{ secrets.POLYGON_TOKEN }}

    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add premarket_smallcaps.md
        mkdir -p $(date +'%Y/%m/%d')
        touch $(date +'%Y/%m/%d')/dummy.md
        git add $(date +'%Y/%m/%d')/*.md
        git commit -m "Update premarket small cap companies list"
        git push
        git push https://x-access-token:${{ secrets.TRADING_GITHUB || secrets.GITHUB_TOKEN }}@github.com/${{ secrets.TRADING_GITHUB || secrets.GITHUB_TOKEN }}.git
      env:
        GITHUB_TOKEN: ${{ secrets.TRADING_GITHUB || secrets.GITHUB_TOKEN || secrets.GH_PAT }}
